name: CI

on:
  push:
    branches: [main, master]

jobs:
  backend-tests:
    name: Backend tests
    runs-on: ubuntu-latest

    defaults:
      run: 
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.jobs
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install dependencies
        run: npm ci 

      - name: Generate Prisma client
        run: npx prisma generate
        env: 
          DATABASE_UR: "file:./test.db"

      - name: Run tests
        run: npm test
        env: 
          DATABASE_URL: "file:./test.db"
          PORT: "3000"
          FRONTEND_ORIGIN: "http://127.0.0.1"
          SESSION_CLIENT: ${{ secrets.SESSION_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

  frontend_tests:
    name: Frontend tests
    runs-on: ubuntu-latest

    defaults: 
      run:
        working-directory: ./frontend_tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.json
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci 

      - name: Run tests
        run: npm test